// AUTO-GENERATED by scripts/generate_qikink_catalog.py from sku_descriptions.xlsx — do not edit by hand.
// Curated wearable, DTG-printable subset of the Qikink SKU catalog (AOP + non-garments excluded).
import { QikinkStyle } from '../pod-catalog.types';

export const QIKINK_APPAREL_CATALOG: QikinkStyle[] = [
  {
    "styleKey": "boy-classic-crew-t-shirt",
    "gender": "Boy",
    "name": "Classic Crew T-Shirt",
    "displayName": "Boys' Classic Crew T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "BRnHs",
    "qikinkBasePriceRupees": 160,
    "colors": [
      {
        "name": "Beige",
        "code": "Be",
        "hex": "#E8DCC5"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Brick Red",
        "code": "BRd",
        "hex": "#9C3B2E"
      },
      {
        "name": "Charcoal Melange",
        "code": "Cm",
        "hex": "#4B5054"
      },
      {
        "name": "Coffee Brown",
        "code": "bn",
        "hex": "#6F4E37"
      },
      {
        "name": "Flag Green",
        "code": "Fgn",
        "hex": "#04724D"
      },
      {
        "name": "Golden Yellow",
        "code": "GYI",
        "hex": "#FFB81C"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Mustard Yellow",
        "code": "MYl",
        "hex": "#D9A521"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "New Yellow",
        "code": "NYl",
        "hex": "#FFD84D"
      },
      {
        "name": "Off White",
        "code": "OFw",
        "hex": "#FAF6EE"
      },
      {
        "name": "Olive Green",
        "code": "OG",
        "hex": "#708238"
      },
      {
        "name": "Orange",
        "code": "or",
        "hex": "#F97316"
      },
      {
        "name": "Petrol Blue",
        "code": "pb",
        "hex": "#2C5F6F"
      },
      {
        "name": "Purple",
        "code": "Pu",
        "hex": "#6B3FA0"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "Royal Blue",
        "code": "Rb",
        "hex": "#2A52BE"
      },
      {
        "name": "SkyBlue",
        "code": "Sb",
        "hex": "#8EC5E8"
      },
      {
        "name": "Steel Grey",
        "code": "SG",
        "hex": "#71797E"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "0_12",
      "12_23",
      "24_35",
      "36_47",
      "5Yrs",
      "7Yrs",
      "9Yrs",
      "11Yrs",
      "13Yrs"
    ]
  },
  {
    "styleKey": "female-baby-tee",
    "gender": "Female",
    "name": "Baby Tee",
    "displayName": "Women's Baby Tee",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "FBbyTrnHs",
    "qikinkBasePriceRupees": 180,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "female-classic-crew-t-shirt",
    "gender": "Female",
    "name": "Classic Crew T-Shirt",
    "displayName": "Women's Classic Crew T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "FRnHs",
    "qikinkBasePriceRupees": 160,
    "colors": [
      {
        "name": "Beige",
        "code": "Be",
        "hex": "#E8DCC5"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Charcoal Melange",
        "code": "Cm",
        "hex": "#4B5054"
      },
      {
        "name": "Coffee Brown",
        "code": "bn",
        "hex": "#6F4E37"
      },
      {
        "name": "Flag Green",
        "code": "Fgn",
        "hex": "#04724D"
      },
      {
        "name": "Golden Yellow",
        "code": "GYI",
        "hex": "#FFB81C"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Mustard Yellow",
        "code": "MYl",
        "hex": "#D9A521"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "New Yellow",
        "code": "NYl",
        "hex": "#FFD84D"
      },
      {
        "name": "Orange",
        "code": "or",
        "hex": "#F97316"
      },
      {
        "name": "Pink",
        "code": "Pk",
        "hex": "#F472B6"
      },
      {
        "name": "Purple",
        "code": "Pu",
        "hex": "#6B3FA0"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "Royal Blue",
        "code": "Rb",
        "hex": "#2A52BE"
      },
      {
        "name": "SkyBlue",
        "code": "Sb",
        "hex": "#8EC5E8"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      },
      {
        "name": "Yellow",
        "code": "Yl",
        "hex": "#FFD400"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "female-crop-tank",
    "gender": "Female",
    "name": "Crop Tank",
    "displayName": "Women's Crop Tank",
    "garmentType": "tank",
    "printTypeId": 1,
    "baseSku": "FFCpTnk",
    "qikinkBasePriceRupees": 125,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Olive Green",
        "code": "OG",
        "hex": "#708238"
      },
      {
        "name": "Purple",
        "code": "Pu",
        "hex": "#6B3FA0"
      },
      {
        "name": "Royal Blue",
        "code": "Rb",
        "hex": "#2A52BE"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "female-crop-top",
    "gender": "Female",
    "name": "Crop Top",
    "displayName": "Women's Crop Top",
    "garmentType": "crop_top",
    "printTypeId": 1,
    "baseSku": "FCpTp",
    "qikinkBasePriceRupees": 150,
    "colors": [
      {
        "name": "Beige",
        "code": "Be",
        "hex": "#E8DCC5"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Golden Yellow",
        "code": "GYI",
        "hex": "#FFB81C"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "SkyBlue",
        "code": "Sb",
        "hex": "#8EC5E8"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "female-cropped-hoodie",
    "gender": "Female",
    "name": "Cropped Hoodie",
    "displayName": "Women's Cropped Hoodie",
    "garmentType": "hoodie",
    "printTypeId": 1,
    "baseSku": "FCpHd",
    "qikinkBasePriceRupees": 345,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Mustard Yellow",
        "code": "MYl",
        "hex": "#D9A521"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "female-kaftan",
    "gender": "Female",
    "name": "Kaftan",
    "displayName": "Women's Kaftan",
    "garmentType": "kaftan",
    "printTypeId": 1,
    "baseSku": "FKftn",
    "qikinkBasePriceRupees": 430,
    "colors": [
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "Freesize"
    ]
  },
  {
    "styleKey": "female-mini-skirt",
    "gender": "Female",
    "name": "Mini Skirt",
    "displayName": "Women's Mini Skirt",
    "garmentType": "skirt",
    "printTypeId": 1,
    "baseSku": "FAOPMiniSkt",
    "qikinkBasePriceRupees": 220,
    "colors": [
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "female-sports-crop-top",
    "gender": "Female",
    "name": "Sports Crop top",
    "displayName": "Women's Sports Crop top",
    "garmentType": "crop_top",
    "printTypeId": 1,
    "baseSku": "FAopSptCrpTOP",
    "qikinkBasePriceRupees": 250,
    "colors": [
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "female-t-shirt-dress",
    "gender": "Female",
    "name": "T-Shirt Dress",
    "displayName": "Women's T-Shirt Dress",
    "garmentType": "dress",
    "printTypeId": 1,
    "baseSku": "FLtFs",
    "qikinkBasePriceRupees": 260,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Golden Yellow",
        "code": "GYI",
        "hex": "#FFB81C"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ]
  },
  {
    "styleKey": "female-tank-top",
    "gender": "Female",
    "name": "Tank Top",
    "displayName": "Women's Tank Top",
    "garmentType": "tank",
    "printTypeId": 1,
    "baseSku": "FTt",
    "qikinkBasePriceRupees": 160,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Charcoal Melange",
        "code": "Cm",
        "hex": "#4B5054"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Pink",
        "code": "Pk",
        "hex": "#F472B6"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ]
  },
  {
    "styleKey": "girl-classic-crew-t-shirt",
    "gender": "Girl",
    "name": "Classic Crew T-Shirt",
    "displayName": "Girls' Classic Crew T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "GRnHs",
    "qikinkBasePriceRupees": 130,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Pink",
        "code": "Pk",
        "hex": "#F472B6"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "Royal Blue",
        "code": "Rb",
        "hex": "#2A52BE"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "0_12",
      "12_23",
      "24_35",
      "36_47",
      "5Yrs",
      "7Yrs",
      "9Yrs",
      "11Yrs",
      "13Yrs"
    ]
  },
  {
    "styleKey": "kids-hoodie",
    "gender": "Kids",
    "name": "Hoodie",
    "displayName": "Kids' Hoodie",
    "garmentType": "hoodie",
    "printTypeId": 1,
    "baseSku": "KHd",
    "qikinkBasePriceRupees": 340,
    "colors": [
      {
        "name": "Baby Pink",
        "code": "BPk",
        "hex": "#F4C2C2"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "Yellow",
        "code": "Yl",
        "hex": "#FFD400"
      }
    ],
    "sizes": [
      "0_12",
      "12_23",
      "24_35",
      "36_47",
      "5Yrs",
      "7Yrs",
      "9Yrs",
      "11Yrs",
      "13Yrs"
    ]
  },
  {
    "styleKey": "kids-rompers",
    "gender": "Kids",
    "name": "Rompers",
    "displayName": "Kids' Rompers",
    "garmentType": "romper",
    "printTypeId": 1,
    "baseSku": "KRp",
    "qikinkBasePriceRupees": 105,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Orchid Blue",
        "code": "Ob",
        "hex": "#6A7BD9"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "Royal Blue",
        "code": "Rb",
        "hex": "#2A52BE"
      },
      {
        "name": "SkyBlue",
        "code": "Sb",
        "hex": "#8EC5E8"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      },
      {
        "name": "Yellow",
        "code": "Yl",
        "hex": "#FFD400"
      }
    ],
    "sizes": [
      "0_5M",
      "6_12M"
    ]
  },
  {
    "styleKey": "male-bike-rider-t-shirt",
    "gender": "Male",
    "name": "Bike Rider T-Shirt",
    "displayName": "Men's Bike Rider T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "MBikrnFs",
    "qikinkBasePriceRupees": 350,
    "colors": [
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "male-classic-crew-t-shirt",
    "gender": "Male",
    "name": "Classic Crew T-Shirt",
    "displayName": "Men's Classic Crew T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "MRnHs",
    "qikinkBasePriceRupees": 290,
    "colors": [
      {
        "name": "Baby Blue",
        "code": "BB",
        "hex": "#A7C7E7"
      },
      {
        "name": "Beige",
        "code": "Be",
        "hex": "#E8DCC5"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Brick Red",
        "code": "BRd",
        "hex": "#9C3B2E"
      },
      {
        "name": "Charcoal Melange",
        "code": "Cm",
        "hex": "#4B5054"
      },
      {
        "name": "Coffee Brown",
        "code": "bn",
        "hex": "#6F4E37"
      },
      {
        "name": "Copper",
        "code": "Cop",
        "hex": "#B87333"
      },
      {
        "name": "Coral",
        "code": "Cor",
        "hex": "#FF7F6A"
      },
      {
        "name": "Flag Green",
        "code": "Fgn",
        "hex": "#04724D"
      },
      {
        "name": "Flamingo",
        "code": "Fl",
        "hex": "#FC8EAC"
      },
      {
        "name": "Golden Yellow",
        "code": "GYI",
        "hex": "#FFB81C"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Jade",
        "code": "Jd",
        "hex": "#00A86B"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Mint",
        "code": "Mnt",
        "hex": "#A8E6CF"
      },
      {
        "name": "Mushroom",
        "code": "Mh",
        "hex": "#BDB2A7"
      },
      {
        "name": "Mustard Yellow",
        "code": "MYl",
        "hex": "#D9A521"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "New Yellow",
        "code": "NYl",
        "hex": "#FFD84D"
      },
      {
        "name": "Off White",
        "code": "OFw",
        "hex": "#FAF6EE"
      },
      {
        "name": "Olive Green",
        "code": "OG",
        "hex": "#708238"
      },
      {
        "name": "Orange",
        "code": "or",
        "hex": "#F97316"
      },
      {
        "name": "Peach",
        "code": "Ph",
        "hex": "#FFCBA4"
      },
      {
        "name": "Petrol Blue",
        "code": "pb",
        "hex": "#2C5F6F"
      },
      {
        "name": "Purple",
        "code": "Pu",
        "hex": "#6B3FA0"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "Royal Blue",
        "code": "Rb",
        "hex": "#2A52BE"
      },
      {
        "name": "SkyBlue",
        "code": "Sb",
        "hex": "#8EC5E8"
      },
      {
        "name": "Steel Grey",
        "code": "SG",
        "hex": "#71797E"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      },
      {
        "name": "Yellow",
        "code": "Yl",
        "hex": "#FFD400"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL",
      "4XL",
      "5XL",
      "6XL",
      "7XL"
    ]
  },
  {
    "styleKey": "male-full-sleeve-t-shirt",
    "gender": "Male",
    "name": "Full Sleeve T-Shirt",
    "displayName": "Men's Full Sleeve T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "MRnFs",
    "qikinkBasePriceRupees": 270,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "Royal Blue",
        "code": "Rb",
        "hex": "#2A52BE"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "male-polo",
    "gender": "Male",
    "name": "Polo",
    "displayName": "Men's Polo",
    "garmentType": "polo",
    "printTypeId": 1,
    "baseSku": "MPHs",
    "qikinkBasePriceRupees": 350,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Brick Red",
        "code": "BRd",
        "hex": "#9C3B2E"
      },
      {
        "name": "Coffee Brown",
        "code": "bn",
        "hex": "#6F4E37"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Mustard Yellow",
        "code": "MYl",
        "hex": "#D9A521"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Petrol Blue",
        "code": "pb",
        "hex": "#2C5F6F"
      },
      {
        "name": "Purple",
        "code": "Pu",
        "hex": "#6B3FA0"
      },
      {
        "name": "Royal Blue",
        "code": "Rb",
        "hex": "#2A52BE"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "male-raglan-t-shirt",
    "gender": "Male",
    "name": "Raglan T-Shirt",
    "displayName": "Men's Raglan T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "MRgFs",
    "qikinkBasePriceRupees": 260,
    "colors": [
      {
        "name": "Black Charcoal Melange",
        "code": "BkCm",
        "hex": "#33383D"
      },
      {
        "name": "Black White",
        "code": "BkWh",
        "hex": "#2B2B2B"
      },
      {
        "name": "White Black",
        "code": "WhBk",
        "hex": "#F5F5F5"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ]
  },
  {
    "styleKey": "male-sleeveless-t-shirt",
    "gender": "Male",
    "name": "Sleeveless T-Shirt",
    "displayName": "Men's Sleeveless T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "MRnSl",
    "qikinkBasePriceRupees": 220,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Charcoal Melange",
        "code": "Cm",
        "hex": "#4B5054"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Olive Green",
        "code": "OG",
        "hex": "#708238"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL",
      "4XL"
    ]
  },
  {
    "styleKey": "male-standard-crew-t-shirt",
    "gender": "Male",
    "name": "Standard Crew T-Shirt",
    "displayName": "Men's Standard Crew T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "MStRnHs",
    "qikinkBasePriceRupees": 170,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "male-v-neck-t-shirt",
    "gender": "Male",
    "name": "V Neck T-Shirt",
    "displayName": "Men's V Neck T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "MVnHs",
    "qikinkBasePriceRupees": 220,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "Royal Blue",
        "code": "Rb",
        "hex": "#2A52BE"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "unisex-acid-wash-hoodie",
    "gender": "Unisex",
    "name": "Acid Wash Hoodie",
    "displayName": "Acid Wash Hoodie",
    "garmentType": "hoodie",
    "printTypeId": 1,
    "baseSku": "UAHD",
    "qikinkBasePriceRupees": 750,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "unisex-acid-wash-oversized-tee",
    "gender": "Unisex",
    "name": "Acid Wash Oversized Tee",
    "displayName": "Acid Wash Oversized Tee",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "UAOsMrnhs",
    "qikinkBasePriceRupees": 380,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Olive Green",
        "code": "OG",
        "hex": "#708238"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "unisex-basic-t-shirt-pc",
    "gender": "Unisex",
    "name": "Basic T-Shirt PC",
    "displayName": "Basic T-Shirt PC",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "UBscRnHs",
    "qikinkBasePriceRupees": 100,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Black melange",
        "code": "Bml",
        "hex": "#3A3A3C"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Navy melange",
        "code": "Nml",
        "hex": "#3A4A6B"
      },
      {
        "name": "Purple",
        "code": "Pu",
        "hex": "#6B3FA0"
      },
      {
        "name": "Purple melange",
        "code": "PMl",
        "hex": "#8B6BAE"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "unisex-cotton-stretch-t-shirt",
    "gender": "Unisex",
    "name": "Cotton Stretch T-Shirt",
    "displayName": "Cotton Stretch T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "UCoSRnHs",
    "qikinkBasePriceRupees": 290,
    "colors": [
      {
        "name": "Baby Blue",
        "code": "BB",
        "hex": "#A7C7E7"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Mint",
        "code": "Mnt",
        "hex": "#A8E6CF"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "unisex-hoodie",
    "gender": "Unisex",
    "name": "Hoodie",
    "displayName": "Hoodie",
    "garmentType": "hoodie",
    "printTypeId": 1,
    "baseSku": "UHd",
    "qikinkBasePriceRupees": 530,
    "colors": [
      {
        "name": "Baby Blue",
        "code": "BB",
        "hex": "#A7C7E7"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Coral",
        "code": "Cor",
        "hex": "#FF7F6A"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Mint",
        "code": "Mnt",
        "hex": "#A8E6CF"
      },
      {
        "name": "Mustard Yellow",
        "code": "MYl",
        "hex": "#D9A521"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Olive Green",
        "code": "OG",
        "hex": "#708238"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "Royal Blue",
        "code": "Rb",
        "hex": "#2A52BE"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "unisex-joggers",
    "gender": "Unisex",
    "name": "Joggers",
    "displayName": "Joggers",
    "garmentType": "joggers",
    "printTypeId": 1,
    "baseSku": "UJog",
    "qikinkBasePriceRupees": 400,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "unisex-oversized-classic-t-shirt",
    "gender": "Unisex",
    "name": "Oversized Classic T-Shirt",
    "displayName": "Oversized Classic T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "UOsMRnHs",
    "qikinkBasePriceRupees": 265,
    "colors": [
      {
        "name": "Baby Blue",
        "code": "BB",
        "hex": "#A7C7E7"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Coral",
        "code": "Cor",
        "hex": "#FF7F6A"
      },
      {
        "name": "Golden Yellow",
        "code": "GYI",
        "hex": "#FFB81C"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Mint",
        "code": "Mnt",
        "hex": "#A8E6CF"
      },
      {
        "name": "Mustard Yellow",
        "code": "MYl",
        "hex": "#D9A521"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Off White",
        "code": "OFw",
        "hex": "#FAF6EE"
      },
      {
        "name": "Olive Green",
        "code": "OG",
        "hex": "#708238"
      },
      {
        "name": "Petrol Blue",
        "code": "pb",
        "hex": "#2C5F6F"
      },
      {
        "name": "Purple",
        "code": "Pu",
        "hex": "#6B3FA0"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "Royal Blue",
        "code": "Rb",
        "hex": "#2A52BE"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "unisex-oversized-hoodie",
    "gender": "Unisex",
    "name": "Oversized Hoodie",
    "displayName": "Oversized Hoodie",
    "garmentType": "hoodie",
    "printTypeId": 1,
    "baseSku": "UOsHd",
    "qikinkBasePriceRupees": 750,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "unisex-oversized-raglan",
    "gender": "Unisex",
    "name": "Oversized Raglan",
    "displayName": "Oversized Raglan",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "UOsRgHs",
    "qikinkBasePriceRupees": 260,
    "colors": [
      {
        "name": "Black Charcoal Melange",
        "code": "BkCm",
        "hex": "#33383D"
      },
      {
        "name": "Black White",
        "code": "BkWh",
        "hex": "#2B2B2B"
      },
      {
        "name": "Coffee Brown off white",
        "code": "BnOw",
        "hex": "#8A6F55"
      },
      {
        "name": "Olive Green off white",
        "code": "OgOw",
        "hex": "#8E9B62"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "unisex-oversized-shirt",
    "gender": "Unisex",
    "name": "Oversized Shirt",
    "displayName": "Oversized Shirt",
    "garmentType": "shirt",
    "printTypeId": 1,
    "baseSku": "UOsMShirtHs",
    "qikinkBasePriceRupees": 390,
    "colors": [
      {
        "name": "Baby Blue",
        "code": "BB",
        "hex": "#A7C7E7"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "unisex-oversized-standard-t-shirt",
    "gender": "Unisex",
    "name": "Oversized Standard T-Shirt",
    "displayName": "Oversized Standard T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "UOSsMRnHs",
    "qikinkBasePriceRupees": 225,
    "colors": [
      {
        "name": "Beige",
        "code": "Be",
        "hex": "#E8DCC5"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "unisex-oversized-sweatshirt",
    "gender": "Unisex",
    "name": "Oversized Sweatshirt",
    "displayName": "Oversized Sweatshirt",
    "garmentType": "sweatshirt",
    "printTypeId": 1,
    "baseSku": "UOSs",
    "qikinkBasePriceRupees": 580,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "unisex-pullover-hoodie",
    "gender": "Unisex",
    "name": "Pullover Hoodie",
    "displayName": "Pullover Hoodie",
    "garmentType": "hoodie",
    "printTypeId": 1,
    "baseSku": "UPuHd",
    "qikinkBasePriceRupees": 490,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Off White",
        "code": "OFw",
        "hex": "#FAF6EE"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "unisex-ringer-t-shirt",
    "gender": "Unisex",
    "name": "Ringer T-shirt",
    "displayName": "Ringer T-shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "URiRnHs",
    "qikinkBasePriceRupees": 200,
    "colors": [
      {
        "name": "Black White",
        "code": "BkWh",
        "hex": "#2B2B2B"
      },
      {
        "name": "Maroon off white",
        "code": "MnOw",
        "hex": "#8E4C5C"
      },
      {
        "name": "Mustard yellow off white",
        "code": "MyOw",
        "hex": "#DDB65A"
      },
      {
        "name": "White Black",
        "code": "WhBk",
        "hex": "#F5F5F5"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "unisex-supima-t-shirt",
    "gender": "Unisex",
    "name": "Supima T-Shirt",
    "displayName": "Supima T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "USuRnHs",
    "qikinkBasePriceRupees": 360,
    "colors": [
      {
        "name": "Beige",
        "code": "Be",
        "hex": "#E8DCC5"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL",
      "4XL",
      "5XL"
    ]
  },
  {
    "styleKey": "unisex-sweatpants",
    "gender": "Unisex",
    "name": "Sweatpants",
    "displayName": "Sweatpants",
    "garmentType": "joggers",
    "printTypeId": 1,
    "baseSku": "USwtpt",
    "qikinkBasePriceRupees": 480,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Off White",
        "code": "OFw",
        "hex": "#FAF6EE"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "unisex-sweatshirt",
    "gender": "Unisex",
    "name": "Sweatshirt",
    "displayName": "Sweatshirt",
    "garmentType": "sweatshirt",
    "printTypeId": 1,
    "baseSku": "USs",
    "qikinkBasePriceRupees": 430,
    "colors": [
      {
        "name": "Baby Blue",
        "code": "BB",
        "hex": "#A7C7E7"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Coral",
        "code": "Cor",
        "hex": "#FF7F6A"
      },
      {
        "name": "Grey Melange",
        "code": "Gm",
        "hex": "#B5B8BC"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Mint",
        "code": "Mnt",
        "hex": "#A8E6CF"
      },
      {
        "name": "Mustard Yellow",
        "code": "MYl",
        "hex": "#D9A521"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Olive Green",
        "code": "OG",
        "hex": "#708238"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "unisex-terry-oversized-tee",
    "gender": "Unisex",
    "name": "Terry Oversized Tee",
    "displayName": "Terry Oversized Tee",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "UOsTMRnHs",
    "qikinkBasePriceRupees": 330,
    "colors": [
      {
        "name": "Baby Blue",
        "code": "BB",
        "hex": "#A7C7E7"
      },
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Flamingo",
        "code": "Fl",
        "hex": "#FC8EAC"
      },
      {
        "name": "Jade",
        "code": "Jd",
        "hex": "#00A86B"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Light Baby Pink",
        "code": "LBp",
        "hex": "#FADADD"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Off White",
        "code": "OFw",
        "hex": "#FAF6EE"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "unisex-terry-shorts",
    "gender": "Unisex",
    "name": "Terry Shorts",
    "displayName": "Terry Shorts",
    "garmentType": "shorts",
    "printTypeId": 1,
    "baseSku": "UTShorts",
    "qikinkBasePriceRupees": 380,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Flamingo",
        "code": "Fl",
        "hex": "#FC8EAC"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "unisex-tie-dye-oversized-t-shirt",
    "gender": "Unisex",
    "name": "Tie Dye Oversized T-Shirt",
    "displayName": "Tie Dye Oversized T-Shirt",
    "garmentType": "tshirt",
    "printTypeId": 1,
    "baseSku": "UOsTiDRnHs",
    "qikinkBasePriceRupees": 450,
    "colors": [
      {
        "name": "Brown Black",
        "code": "BrBk",
        "hex": "#3E2B23"
      },
      {
        "name": "Green Black",
        "code": "GrBk",
        "hex": "#2F4538"
      },
      {
        "name": "White Black",
        "code": "WhBk",
        "hex": "#F5F5F5"
      },
      {
        "name": "White Lavender",
        "code": "WhLv",
        "hex": "#EDE4F7"
      },
      {
        "name": "Yellow",
        "code": "Yl",
        "hex": "#FFD400"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "unisex-tie-dye-shorts",
    "gender": "Unisex",
    "name": "Tie Dye Shorts",
    "displayName": "Tie Dye Shorts",
    "garmentType": "shorts",
    "printTypeId": 1,
    "baseSku": "UTiDShorts",
    "qikinkBasePriceRupees": 430,
    "colors": [
      {
        "name": "Brown Black",
        "code": "BrBk",
        "hex": "#3E2B23"
      },
      {
        "name": "Green Black",
        "code": "GrBk",
        "hex": "#2F4538"
      },
      {
        "name": "White Black",
        "code": "WhBk",
        "hex": "#F5F5F5"
      },
      {
        "name": "White Lavender",
        "code": "WhLv",
        "hex": "#EDE4F7"
      },
      {
        "name": "Yellow",
        "code": "Yl",
        "hex": "#FFD400"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ]
  },
  {
    "styleKey": "unisex-varsity-jacket",
    "gender": "Unisex",
    "name": "Varsity Jacket",
    "displayName": "Varsity Jacket",
    "garmentType": "jacket",
    "printTypeId": 1,
    "baseSku": "UVarJac",
    "qikinkBasePriceRupees": 825,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "Bottle Green",
        "code": "Gn",
        "hex": "#14532D"
      },
      {
        "name": "Lavender",
        "code": "Lv",
        "hex": "#C5A3E0"
      },
      {
        "name": "Maroon",
        "code": "Mn",
        "hex": "#6E1F2E"
      },
      {
        "name": "Navy Blue",
        "code": "Nb",
        "hex": "#1F2A44"
      },
      {
        "name": "Red",
        "code": "Rd",
        "hex": "#D32F2F"
      }
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  },
  {
    "styleKey": "unisex-zip-hoodie",
    "gender": "Unisex",
    "name": "Zip Hoodie",
    "displayName": "Zip Hoodie",
    "garmentType": "hoodie",
    "printTypeId": 1,
    "baseSku": "UHwZHd",
    "qikinkBasePriceRupees": 830,
    "colors": [
      {
        "name": "Black",
        "code": "Bk",
        "hex": "#1A1A1A"
      },
      {
        "name": "White",
        "code": "Wh",
        "hex": "#FFFFFF"
      }
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ]
  }
];
